services:
  devcon:
    user: devcon
    image: hadirgax/devcontainer-miniconda:latest
    platform: linux/amd64
    volumes:
      - ..:/workspace:cached
      - conda-pkgs-cache:/home/devcon/.conda/pkgs
    command: /bin/bash -c "while sleep 1000; do :; done"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 16G
        reservations:
          cpus: '0.5'
          memory: 512M
          devices:
            - driver: nvidia
              capabilities: [gpu]

volumes:
  conda-pkgs-cache:
